apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: httpd
  template:
    metadata:
      labels:
        app.kubernetes.io/component: httpd
    spec:
      containers:
        - name: cern-httpd
          image: jessews/cern-httpd:history
          args: ["-v"]
          ports:
            - name: http
              containerPort: 80
          resources:
              requests:
                cpu: 10m
                memory: 16Mi
              limits:
                cpu: 50m
                memory: 32Mi
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 8
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 30
            timeoutSeconds: 5