name: Docker image CI

on:
  push:
    branches: master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image - base
        id: docker_build_base
        uses: docker/build-push-action@v2
        with:
          push: true
          file: Dockerfile
          tags: |
            jessews/cern-httpd:latest,
            jessews/cern-httpd:base,
            jessews/cern-httpd:3.0a
      - name: Image digest - base
        run: echo "${{ steps.docker_build_base.outputs.digest }}

      - name: Build and push image - history
        id: docker_build_history
        uses: docker/build-push-action@v2
        with:
          push: true
          file: Dockerfile-history
          tags: |
            jessews/cern-httpd:history,
            jessews/cern-httpd:3.0a-history
      - name: Image digest - history
        run: echo "${{ steps.docker_build_history.outputs.digest }}
